In [1]:
import pandas as pd
import numpy as np
from datetime import date

In [2]:
station_df = pd.read_csv('./station.csv')
station_df

,station_id,name,lat,long,install_date,install_dockcount,modification_date,current_dockcount,decommission_date
0,BT-01,3rd Ave & Broad St,47.618418,-122.350964,10/13/2014,18,NaN,18,NaN
1,BT-03,2nd Ave & Vine St,47.615829,-122.348564,10/13/2014,16,NaN,16,NaN
2,BT-04,6th Ave & Blanchard St,47.616094,-122.341102,10/13/2014,16,NaN,16,NaN
3,BT-05,2nd Ave & Blanchard St,47.613110,-122.344208,10/13/2014,14,NaN,14,NaN
4,CBD-03,7th Ave & Union St,47.610731,-122.332447,10/13/2014,20,NaN,20,NaN
5,CBD-04,Union St & 4th Ave,47.609221,-122.335596,7/27/2015,18,NaN,18,NaN
6,CBD-05,1st Ave & Marion St,47.604058,-122.335800,10/13/2014,20,NaN,20,NaN
7,CBD-06,2nd Ave & Spring St,47.605950,-122.335768,10/13/2014,20,11/9/2015,18,NaN
8,CBD-07,City Hall / 4th Ave & James St,47.603509,-122.330409,10/13/2014,20,NaN,20,NaN
9,CBD-13,2nd Ave & Pine St,47.610185,-122.339641,10/13/2014,18,NaN,18,NaN
10,CD-01,12th Ave & E Yesler Way,47.602103,-122.316923,5/22/2015,16,8/9/2016,0,8/9/2016
11,CH-01,Summit Ave & E Denny Way,47.618633,-122.325249,10/13/2014,16,NaN,16,NaN
12,CH-02,E Harrison St & Broadway Ave E,47.622063,-122.321251,10/13/2014,18,2/24/2015,20,NaN
13,CH-03,Summit Ave E & E Republican St,47.623367,-122.325279,10/13/2014,16,NaN,16,NaN
14,CH-05,15th Ave E & E Thomas St,47.620712,-122.312805,10/13/2014,16,NaN,16,NaN
15,CH-06,12th Ave & E Denny Way,47.618549,-122.317017,10/13/2014,16,NaN,16,NaN
16,CH-07,E Pine St & 16th Ave,47.615330,-122.311752,10/13/2014,18,NaN,18,NaN
17,CH-08,Cal Anderson Park / 11th Ave & Pine St,47.615486,-122.318245,10/13/2014,28,2/24/2015,26,NaN
18,CH-09,Harvard Ave & E Pine St,47.615517,-122.322083,10/13/2014,16,NaN,16,NaN
19,CH-12,Bellevue Ave & E Pine St,47.615456,-122.326729,10/13/2014,18,NaN,14,NaN
20,CH-15,12th Ave & E Mercer St,47.624142,-122.316811,10/13/2014,16,NaN,16,NaN
21,DPD-01,9th Ave N & Mercer St,47.624298,-122.339617,10/13/2014,18,NaN,18,NaN
22,DPD-03,Children's Hospital / Sandpoint Way NE & 40th ...,47.663509,-122.284119,10/13/2014,30,3/24/2015,24,NaN
23,EL-01,Fred Hutchinson Cancer Research Center / Fairv...,47.627643,-122.332576,10/13/2014,12,3/27/2015,16,NaN
24,EL-03,E Blaine St & Fairview Ave E,47.634831,-122.326634,10/13/2014,18,NaN,18,NaN
25,EL-05,Eastlake Ave E & E Allison St,47.649090,-122.322983,10/13/2014,18,NaN,18,NaN
26,FH-01,Frye Art Museum / Terry Ave & Columbia St,47.607281,-122.324783,10/13/2014,16,3/18/2016,0,3/18/2016
27,FH-04,Seattle University / E Columbia St & 12th Ave,47.609239,-122.316651,10/13/2014,20,NaN,20,NaN
28,ID-04,6th Ave S & S King St,47.598488,-122.326412,10/13/2014,16,NaN,16,NaN
29,PS-04,Occidental Park / Occidental Ave S & S Washing...,47.600757,-122.332946,10/13/2014,18,NaN,18,NaN
30,PS-05,King Street Station Plaza / 2nd Ave Extension ...,47.598994,-122.329684,10/13/2014,18,NaN,18,NaN
31,SLU-01,REI / Yale Ave N & John St,47.619859,-122.330304,10/13/2014,18,2/24/2015,20,NaN
32,SLU-02,Dexter Ave N & Aloha St,47.627735,-122.342232,10/13/2014,18,NaN,18,NaN
33,SLU-04,Republican St & Westlake Ave N,47.623165,-122.338203,10/13/2014,18,NaN,18,NaN
34,SLU-07,PATH / 9th Ave & Westlake Ave,47.618320,-122.338913,10/13/2014,18,NaN,18,NaN
35,SLU-15,Westlake Ave & 6th Ave,47.613628,-122.337341,10/13/2014,12,3/13/2015,20,NaN
36,SLU-16,Pine St & 9th Ave,47.613715,-122.331777,10/13/2014,20,NaN,20,NaN
37,SLU-17,Lake Union Park / Valley St & Boren Ave N,47.626041,-122.335831,10/13/2014,18,2/23/2015,16,NaN
38,SLU-18,Dexter Ave & Denny Way,47.618285,-122.342205,10/13/2014,20,11/2/2015,0,7/2/2016
39,SLU-19,Key Arena / 1st Ave N & Harrison St,47.622277,-122.355230,10/13/2014,12,3/4/2015,16,NaN
40,SLU-20,Terry Ave & Stewart St,47.616260,-122.333815,6/12/2015,20,NaN,20,NaN
41,SLU-21,Mercer St & 9th Ave N,47.624769,-122.339408,9/15/2015,20,NaN,20,NaN
42,UD-01,Burke-Gilman Trail / NE Blakeley St & 24th Ave NE,47.666145,-122.301491,10/13/2014,18,NaN,18,NaN
43,UD-02,NE 42nd St & University Way NE,47.658288,-122.313334,10/13/2014,18,NaN,18,NaN
44,UD-04,12th Ave & NE Campus Pkwy,47.656395,-122.315620,10/13/2014,16,NaN,16,NaN
45,UD-07,NE 47th St & 12th Ave NE,47.663143,-122.315086,10/13/2014,16,NaN,16,NaN
46,UW-01,UW McCarty Hall / Whitman Ct,47.660268,-122.304826,10/13/2014,16,10/29/2015,0,10/29/2015
47,UW-02,Burke Museum / E Stevens Way NE & Memorial Way NE,47.659756,-122.310402,10/13/2014,12,2/20/2015,14,NaN
48,UW-04,15th Ave NE & NE 40th St,47.655590,-122.311890,10/13/2014,18,2/20/2015,16,NaN
49,UW-06,UW Engineering Library / E Stevens Way NE & Je...,47.654613,-122.304863,10/13/2014,12,2/20/2015,14,NaN
50,UW-07,UW Intramural Activities Building,47.653713,-122.302162,10/13/2014,20,2/20/2015,14,NaN
51,UW-10,UW Magnuson Health Sciences Center Rotunda / C...,47.650725,-122.311188,10/13/2014,16,NaN,16,NaN
52,WF-01,Pier 69 / Alaskan Way & Clay St,47.614315,-122.354093,10/13/2014,18,NaN,24,NaN
53,WF-04,Seattle Aquarium / Alaskan Way S & Elliott Bay...,47.607702,-122.341650,10/13/2014,18,NaN,18,NaN
54,CH-16,Broadway and E Denny Way,47.618640,-122.320777,3/18/2016,18,NaN,18,NaN
55,SLU-22,Thomas St & 5th Ave N,47.620879,-122.347377,7/3/2016,18,NaN,18,NaN
56,UW-11,NE Pacific St/UW Medical Center,47.649952,-122.306263,10/29/2015,16,NaN,16,NaN
57,WF-03,Pier 66 / Alaskan Way & Bell St,47.611370,-122.348701,8/9/2016,18,NaN,18,NaN

In [3]:
trip_df= pd.read_csv('./trip.csv', skiprows=[50793]).drop_duplicates()
trip_df

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_name,to_station_name,from_station_id,to_station_id,usertype,gender,birthyear
0,431,10/13/2014 10:31,10/13/2014 10:48,SEA00298,985.935,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,1960.0
1,432,10/13/2014 10:32,10/13/2014 10:48,SEA00195,926.375,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,1970.0
2,433,10/13/2014 10:33,10/13/2014 10:48,SEA00486,883.831,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Female,1988.0
3,434,10/13/2014 10:34,10/13/2014 10:48,SEA00333,865.937,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Female,1977.0
4,435,10/13/2014 10:34,10/13/2014 10:49,SEA00202,923.923,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,1971.0
5,436,10/13/2014 10:34,10/13/2014 10:47,SEA00337,808.805,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,1974.0
6,437,10/13/2014 11:35,10/13/2014 11:45,SEA00202,596.715,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Male,1978.0
7,438,10/13/2014 11:35,10/13/2014 11:45,SEA00311,592.131,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Male,1983.0
8,439,10/13/2014 11:35,10/13/2014 11:45,SEA00486,586.347,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Female,1974.0
9,440,10/13/2014 11:35,10/13/2014 11:45,SEA00434,587.634,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Male,1958.0
10,441,10/13/2014 11:36,10/13/2014 11:45,SEA00195,564.899,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Female,1983.0
11,442,10/13/2014 11:37,10/13/2014 11:47,SEA00101,620.141,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Male,1982.0
12,443,10/13/2014 11:37,10/13/2014 11:47,SEA00461,634.087,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Male,1984.0
13,444,10/13/2014 11:37,10/13/2014 11:47,SEA00044,614.336,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Male,1955.0
14,445,10/13/2014 11:37,10/13/2014 11:47,SEA00298,601.463,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Male,1953.0
15,446,10/13/2014 11:37,10/13/2014 11:47,SEA00106,618.781,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Female,1958.0
16,447,10/13/2014 11:37,10/13/2014 11:47,SEA00108,617.085,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Male,1959.0
17,448,10/13/2014 11:37,10/13/2014 11:47,SEA00236,600.050,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Male,1950.0
18,450,10/13/2014 11:40,10/13/2014 11:49,SEA00107,499.734,Occidental Park / Occidental Ave S & S Washing...,City Hall / 4th Ave & James St,PS-04,CBD-07,Member,Female,1976.0
19,452,10/13/2014 11:41,10/13/2014 11:51,SEA00259,575.307,Occidental Park / Occidental Ave S & S Washing...,1st Ave & Marion St,PS-04,CBD-05,Member,Male,1986.0
20,453,10/13/2014 11:41,10/13/2014 11:51,SEA00178,571.807,Occidental Park / Occidental Ave S & S Washing...,1st Ave & Marion St,PS-04,CBD-05,Member,Male,1953.0
21,454,10/13/2014 11:41,10/13/2014 11:51,SEA00123,563.763,Occidental Park / Occidental Ave S & S Washing...,1st Ave & Marion St,PS-04,CBD-05,Member,Male,1986.0
22,455,10/13/2014 11:42,10/13/2014 11:49,SEA00373,437.689,Occidental Park / Occidental Ave S & S Washing...,City Hall / 4th Ave & James St,PS-04,CBD-07,Member,Male,1967.0
23,456,10/13/2014 11:43,10/13/2014 11:51,SEA00121,483.154,Occidental Park / Occidental Ave S & S Washing...,1st Ave & Marion St,PS-04,CBD-05,Member,Female,1986.0
24,457,10/13/2014 11:43,10/13/2014 11:51,SEA00029,479.382,Occidental Park / Occidental Ave S & S Washing...,1st Ave & Marion St,PS-04,CBD-05,Member,Female,1987.0
25,458,10/13/2014 11:43,10/13/2014 11:52,SEA00436,533.532,Occidental Park / Occidental Ave S & S Washing...,1st Ave & Marion St,PS-04,CBD-05,Member,Female,1987.0
26,459,10/13/2014 11:43,10/13/2014 11:51,SEA00118,481.629,Occidental Park / Occidental Ave S & S Washing...,1st Ave & Marion St,PS-04,CBD-05,Member,Male,1974.0
27,460,10/13/2014 11:43,10/13/2014 11:51,SEA00177,460.772,Occidental Park / Occidental Ave S & S Washing...,1st Ave & Marion St,PS-04,CBD-05,Member,Male,1967.0
28,461,10/13/2014 11:43,10/13/2014 11:51,SEA00348,459.165,Occidental Park / Occidental Ave S & S Washing...,1st Ave & Marion St,PS-04,CBD-05,Member,Female,1983.0
29,462,10/13/2014 11:44,10/13/2014 11:55,SEA00459,680.457,Occidental Park / Occidental Ave S & S Washing...,2nd Ave & Spring St,PS-04,CBD-06,Member,Male,1970.0
...,...,...,...,...,...,...,...,...,...,...,...,...
286827,255216,8/31/2016 20:13,8/31/2016 20:34,SEA00309,1233.725,3rd Ave & Broad St,Pier 66 / Alaskan Way & Bell St,BT-01,WF-03,Short-Term Pass Holder,NaN,NaN
286828,255217,8/31/2016 20:32,8/31/2016 20:56,SEA00034,1472.611,6th Ave S & S King St,Cal Anderson Park / 11th Ave & Pine St,ID-04,CH-08,Short-Term Pass Holder,NaN,NaN
286829,255218,8/31/2016 20:32,8/31/2016 20:56,SEA00023,1462.959,6th Ave S & S King St,Cal Anderson Park / 11th Ave & Pine St,ID-04,CH-08,Short-Term Pass Holder,NaN,NaN
286830,255219,8/31/2016 20:32,8/31/2016 20:54,SEA00499,1275.800,2nd Ave & Spring St,Harvard Ave & E Pine St,CBD-06,CH-09,Short-Term Pass Holder,NaN,NaN
286831,255220,8/31/2016 20:33,8/31/2016 20:56,SEA00490,1403.165,6th Ave S & S King St,Cal Anderson Park / 11th Ave & Pine St,ID-04,CH-08,Short-Term Pass Holder,NaN,NaN
286832,255221,8/31/2016 20:33,8/31/2016 20:57,SEA00442,1411.592,6th Ave S & S King St,Cal Anderson Park / 11th Ave & Pine St,ID-04,CH-08,Short-Term Pass Holder,NaN,NaN
286833,255222,8/31/2016 20:33,8/31/2016 20:36,SEA00297,193.605,Summit Ave E & E Republican St,REI / Yale Ave N & John St,CH-03,SLU-01,Member,Male,1978.0
286834,255223,8/31/2016 20:43,8/31/2016 20:47,SEA00321,270.934,15th Ave E & E Thomas St,Bellevue Ave & E Pine St,CH-05,CH-12,Member,Male,1988.0
286835,255224,8/31/2016 20:44,8/31/2016 20:48,SEA00116,214.717,Union St & 4th Ave,Westlake Ave & 6th Ave,CBD-04,SLU-15,Member,Male,1985.0
286836,255225,8/31/2016 20:57,8/31/2016 21:00,SEA00247,187.685,12th Ave & E Mercer St,Cal Anderson Park / 11th Ave & Pine St,CH-15,CH-08,Member,Male,1995.0
286837,255226,8/31/2016 20:58,8/31/2016 21:02,SEA00164,271.667,Seattle University / E Columbia St & 12th Ave,Cal Anderson Park / 11th Ave & Pine St,FH-04,CH-08,Short-Term Pass Holder,NaN,NaN
286838,255227,8/31/2016 20:58,8/31/2016 21:02,SEA00107,273.808,Seattle University / E Columbia St & 12th Ave,Cal Anderson Park / 11th Ave & Pine St,FH-04,CH-08,Short-Term Pass Holder,NaN,NaN
286839,255228,8/31/2016 21:11,8/31/2016 21:15,SEA00499,235.553,Harvard Ave & E Pine St,E Harrison St & Broadway Ave E,CH-09,CH-02,Member,Male,1987.0
286840,255229,8/31/2016 21:16,8/31/2016 21:32,SEA00045,970.096,Summit Ave & E Denny Way,Thomas St & 5th Ave N,CH-01,SLU-22,Member,Male,1994.0
286841,255230,8/31/2016 21:27,8/31/2016 21:30,SEA00056,198.324,Republican St & Westlake Ave N,Dexter Ave N & Aloha St,SLU-04,SLU-02,Member,Male,1981.0
286842,255231,8/31/2016 21:35,8/31/2016 21:46,SEA00288,671.917,NE Pacific St/UW Medical Center,Burke-Gilman Trail / NE Blakeley St & 24th Ave NE,UW-11,UD-01,Member,Female,1976.0
286843,255232,8/31/2016 21:59,8/31/2016 22:04,SEA00499,308.484,E Harrison St & Broadway Ave E,Bellevue Ave & E Pine St,CH-02,CH-12,Member,Male,1989.0
286844,255233,8/31/2016 22:02,8/31/2016 22:17,SEA00074,905.417,Key Arena / 1st Ave N & Harrison St,Pier 66 / Alaskan Way & Bell St,SLU-19,WF-03,Member,Female,1974.0
286845,255234,8/31/2016 22:02,8/31/2016 22:17,SEA00448,879.160,Key Arena / 1st Ave N & Harrison St,Pier 66 / Alaskan Way & Bell St,SLU-19,WF-03,Member,Male,1981.0
286846,255235,8/31/2016 22:10,8/31/2016 22:28,SEA00144,1084.191,Seattle Aquarium / Alaskan Way S & Elliott Bay...,Key Arena / 1st Ave N & Harrison St,WF-04,SLU-19,Short-Term Pass Holder,NaN,NaN
286847,255236,8/31/2016 22:13,8/31/2016 22:25,SEA00254,674.993,3rd Ave & Broad St,Occidental Park / Occidental Ave S & S Washing...,BT-01,PS-04,Member,Male,1984.0
286848,255237,8/31/2016 22:37,8/31/2016 22:39,SEA00330,144.477,Summit Ave & E Denny Way,Summit Ave E & E Republican St,CH-01,CH-03,Member,Male,1990.0
286849,255238,8/31/2016 22:44,8/31/2016 23:03,SEA00336,1106.063,Pier 69 / Alaskan Way & Clay St,2nd Ave & Blanchard St,WF-01,BT-05,Short-Term Pass Holder,NaN,NaN
286850,255239,8/31/2016 22:44,8/31/2016 23:03,SEA00394,1116.502,Pier 69 / Alaskan Way & Clay St,2nd Ave & Blanchard St,WF-01,BT-05,Short-Term Pass Holder,NaN,NaN
286851,255240,8/31/2016 22:47,8/31/2016 23:03,SEA00370,920.672,Pier 69 / Alaskan Way & Clay St,2nd Ave & Blanchard St,WF-01,BT-05,Short-Term Pass Holder,NaN,NaN
286852,255241,8/31/2016 23:34,8/31/2016 23:45,SEA00201,679.532,Harvard Ave & E Pine St,2nd Ave & Spring St,CH-09,CBD-06,Short-Term Pass Holder,NaN,NaN
286853,255242,8/31/2016 23:48,9/1/2016 0:20,SEA00247,1965.418,Cal Anderson Park / 11th Ave & Pine St,6th Ave S & S King St,CH-08,ID-04,Short-Term Pass Holder,NaN,NaN
286854,255243,8/31/2016 23:47,9/1/2016 0:20,SEA00300,1951.173,Cal Anderson Park / 11th Ave & Pine St,6th Ave S & S King St,CH-08,ID-04,Short-Term Pass Holder,NaN,NaN
286855,255244,8/31/2016 23:49,9/1/2016 0:20,SEA00047,1883.299,Cal Anderson Park / 11th Ave & Pine St,6th Ave S & S King St,CH-08,ID-04,Short-Term Pass Holder,NaN,NaN
286856,255245,8/31/2016 23:49,9/1/2016 0:20,SEA00442,1896.031,Cal Anderson Park / 11th Ave & Pine St,6th Ave S & S King St,CH-08,ID-04,Short-Term Pass Holder,NaN,NaN

In [4]:
weather_df = pd.read_csv('./weather.csv')
weather_df.head()

,Date,Max_Temperature_F,Mean_Temperature_F,Min_TemperatureF,Max_Dew_Point_F,MeanDew_Point_F,Min_Dewpoint_F,Max_Humidity,Mean_Humidity,Min_Humidity,...,Mean_Sea_Level_Pressure_In,Min_Sea_Level_Pressure_In,Max_Visibility_Miles,Mean_Visibility_Miles,Min_Visibility_Miles,Max_Wind_Speed_MPH,Mean_Wind_Speed_MPH,Max_Gust_Speed_MPH,Precipitation_In,Events
0,10/13/2014,71,62.0,54,55,51,46,87,68,46,...,29.79,29.65,10,10,4,13,4,21,0.00,Rain
1,10/14/2014,63,59.0,55,52,51,50,88,78,63,...,29.75,29.54,10,9,3,10,5,17,0.11,Rain
2,10/15/2014,62,58.0,54,53,50,46,87,77,67,...,29.71,29.51,10,9,3,18,7,25,0.45,Rain
3,10/16/2014,71,61.0,52,49,46,42,83,61,36,...,29.95,29.81,10,10,10,9,4,-,0.00,Rain
4,10/17/2014,64,60.0,57,55,51,41,87,72,46,...,29.78,29.73,10,10,6,8,3,-,0.14,Rain

# 1. What is the average trip duration for a borrowed bicycle?

In [5]:
trip_df['tripduration'].mean()

1202.6122102556499

# 2. What's the most common age of a bicycle-sharer?

In [6]:
pd.DataFrame(trip_df['birthyear'].groupby(trip_df.birthyear).count()).sort_values(by='birthyear', ascending=False).head(1)

           birthyear
birthyear
1987.0         13904

# 3. Given all the weather data here, find the average precipitation per month, and the median precipitation.

In [7]:
weather_df['Date'] = pd.to_datetime(weather_df['Date'])
weather_df['Month'] = weather_df['Date'].dt.month
pd.DataFrame(weather_df['Precipitation_In'].groupby(weather_df.Month).mean())

       Precipitation_In
Month
1              0.143548
2              0.168421
3              0.156935
4              0.051333
5              0.012419
6              0.030500
7              0.012097
8              0.018226
9              0.041000
10             0.189000
11             0.187833
12             0.236290

In [8]:
pd.DataFrame(weather_df['Precipitation_In'].groupby(weather_df.Month).median())

       Precipitation_In
Month
1                 0.020
2                 0.040
3                 0.025
4                 0.000
5                 0.000
6                 0.000
7                 0.000
8                 0.000
9                 0.000
10                0.040
11                0.035
12                0.100

# 4. What’s the average number of bikes at a given bike station?

In [9]:
station_df['average_dockcount'] = (station_df.install_dockcount + station_df.current_dockcount) // 2

In [10]:
station_df[['station_id', 'name', 'average_dockcount']]

,station_id,name,average_dockcount
0,BT-01,3rd Ave & Broad St,18
1,BT-03,2nd Ave & Vine St,16
2,BT-04,6th Ave & Blanchard St,16
3,BT-05,2nd Ave & Blanchard St,14
4,CBD-03,7th Ave & Union St,20
5,CBD-04,Union St & 4th Ave,18
6,CBD-05,1st Ave & Marion St,20
7,CBD-06,2nd Ave & Spring St,19
8,CBD-07,City Hall / 4th Ave & James St,20
9,CBD-13,2nd Ave & Pine St,18
10,CD-01,12th Ave & E Yesler Way,8
11,CH-01,Summit Ave & E Denny Way,16
12,CH-02,E Harrison St & Broadway Ave E,19
13,CH-03,Summit Ave E & E Republican St,16
14,CH-05,15th Ave E & E Thomas St,16
15,CH-06,12th Ave & E Denny Way,16
16,CH-07,E Pine St & 16th Ave,18
17,CH-08,Cal Anderson Park / 11th Ave & Pine St,27
18,CH-09,Harvard Ave & E Pine St,16
19,CH-12,Bellevue Ave & E Pine St,16
20,CH-15,12th Ave & E Mercer St,16
21,DPD-01,9th Ave N & Mercer St,18
22,DPD-03,Children's Hospital / Sandpoint Way NE & 40th ...,27
23,EL-01,Fred Hutchinson Cancer Research Center / Fairv...,14
24,EL-03,E Blaine St & Fairview Ave E,18
25,EL-05,Eastlake Ave E & E Allison St,18
26,FH-01,Frye Art Museum / Terry Ave & Columbia St,8
27,FH-04,Seattle University / E Columbia St & 12th Ave,20
28,ID-04,6th Ave S & S King St,16
29,PS-04,Occidental Park / Occidental Ave S & S Washing...,18
30,PS-05,King Street Station Plaza / 2nd Ave Extension ...,18
31,SLU-01,REI / Yale Ave N & John St,19
32,SLU-02,Dexter Ave N & Aloha St,18
33,SLU-04,Republican St & Westlake Ave N,18
34,SLU-07,PATH / 9th Ave & Westlake Ave,18
35,SLU-15,Westlake Ave & 6th Ave,16
36,SLU-16,Pine St & 9th Ave,20
37,SLU-17,Lake Union Park / Valley St & Boren Ave N,17
38,SLU-18,Dexter Ave & Denny Way,10
39,SLU-19,Key Arena / 1st Ave N & Harrison St,14
40,SLU-20,Terry Ave & Stewart St,20
41,SLU-21,Mercer St & 9th Ave N,20
42,UD-01,Burke-Gilman Trail / NE Blakeley St & 24th Ave NE,18
43,UD-02,NE 42nd St & University Way NE,18
44,UD-04,12th Ave & NE Campus Pkwy,16
45,UD-07,NE 47th St & 12th Ave NE,16
46,UW-01,UW McCarty Hall / Whitman Ct,8
47,UW-02,Burke Museum / E Stevens Way NE & Memorial Way NE,13
48,UW-04,15th Ave NE & NE 40th St,17
49,UW-06,UW Engineering Library / E Stevens Way NE & Je...,13
50,UW-07,UW Intramural Activities Building,17
51,UW-10,UW Magnuson Health Sciences Center Rotunda / C...,16
52,WF-01,Pier 69 / Alaskan Way & Clay St,21
53,WF-04,Seattle Aquarium / Alaskan Way S & Elliott Bay...,18
54,CH-16,Broadway and E Denny Way,18
55,SLU-22,Thomas St & 5th Ave N,18
56,UW-11,NE Pacific St/UW Medical Center,16
57,WF-03,Pier 66 / Alaskan Way & Bell St,18

# 5. When a bike station is modified, is it more likely that it’ll lose bikes or gain bikes? How do you know?

In [11]:
diff = station_df.dropna(subset=['modification_date'])

In [12]:
diff.count()

station_id           17
name                 17
lat                  17
long                 17
install_date         17
install_dockcount    17
modification_date    17
current_dockcount    17
decommission_date     4
average_dockcount    17
dtype: int64

In [13]:
diff[diff['install_dockcount'] > diff['current_dockcount']].count()

station_id           10
name                 10
lat                  10
long                 10
install_date         10
install_dockcount    10
modification_date    10
current_dockcount    10
decommission_date     4
average_dockcount    10
dtype: int64

It is more likely because there is more instances where there is less bikes after modification date.

# 6. Display the information for bike stations that have been modified.

In [14]:
diff

,station_id,name,lat,long,install_date,install_dockcount,modification_date,current_dockcount,decommission_date,average_dockcount
7,CBD-06,2nd Ave & Spring St,47.605950,-122.335768,10/13/2014,20,11/9/2015,18,NaN,19
10,CD-01,12th Ave & E Yesler Way,47.602103,-122.316923,5/22/2015,16,8/9/2016,0,8/9/2016,8
12,CH-02,E Harrison St & Broadway Ave E,47.622063,-122.321251,10/13/2014,18,2/24/2015,20,NaN,19
17,CH-08,Cal Anderson Park / 11th Ave & Pine St,47.615486,-122.318245,10/13/2014,28,2/24/2015,26,NaN,27
22,DPD-03,Children's Hospital / Sandpoint Way NE & 40th ...,47.663509,-122.284119,10/13/2014,30,3/24/2015,24,NaN,27
23,EL-01,Fred Hutchinson Cancer Research Center / Fairv...,47.627643,-122.332576,10/13/2014,12,3/27/2015,16,NaN,14
26,FH-01,Frye Art Museum / Terry Ave & Columbia St,47.607281,-122.324783,10/13/2014,16,3/18/2016,0,3/18/2016,8
31,SLU-01,REI / Yale Ave N & John St,47.619859,-122.330304,10/13/2014,18,2/24/2015,20,NaN,19
35,SLU-15,Westlake Ave & 6th Ave,47.613628,-122.337341,10/13/2014,12,3/13/2015,20,NaN,16
37,SLU-17,Lake Union Park / Valley St & Boren Ave N,47.626041,-122.335831,10/13/2014,18,2/23/2015,16,NaN,17
38,SLU-18,Dexter Ave & Denny Way,47.618285,-122.342205,10/13/2014,20,11/2/2015,0,7/2/2016,10
39,SLU-19,Key Arena / 1st Ave N & Harrison St,47.622277,-122.355230,10/13/2014,12,3/4/2015,16,NaN,14
46,UW-01,UW McCarty Hall / Whitman Ct,47.660268,-122.304826,10/13/2014,16,10/29/2015,0,10/29/2015,8
47,UW-02,Burke Museum / E Stevens Way NE & Memorial Way NE,47.659756,-122.310402,10/13/2014,12,2/20/2015,14,NaN,13
48,UW-04,15th Ave NE & NE 40th St,47.655590,-122.311890,10/13/2014,18,2/20/2015,16,NaN,17
49,UW-06,UW Engineering Library / E Stevens Way NE & Je...,47.654613,-122.304863,10/13/2014,12,2/20/2015,14,NaN,13
50,UW-07,UW Intramural Activities Building,47.653713,-122.302162,10/13/2014,20,2/20/2015,14,NaN,17

# 7. Display the bike stations that have been decommisioned.

In [15]:
decom = station_df.dropna(subset=['decommission_date'])

In [16]:
decom

,station_id,name,lat,long,install_date,install_dockcount,modification_date,current_dockcount,decommission_date,average_dockcount
10,CD-01,12th Ave & E Yesler Way,47.602103,-122.316923,5/22/2015,16,8/9/2016,0,8/9/2016,8
26,FH-01,Frye Art Museum / Terry Ave & Columbia St,47.607281,-122.324783,10/13/2014,16,3/18/2016,0,3/18/2016,8
38,SLU-18,Dexter Ave & Denny Way,47.618285,-122.342205,10/13/2014,20,11/2/2015,0,7/2/2016,10
46,UW-01,UW McCarty Hall / Whitman Ct,47.660268,-122.304826,10/13/2014,16,10/29/2015,0,10/29/2015,8

# 8. Display the decommissioned bike station that had the highest average bike count

In [17]:
decom.sort_values(by='average_dockcount', ascending=False).head(1)

,station_id,name,lat,long,install_date,install_dockcount,modification_date,current_dockcount,decommission_date,average_dockcount
38,SLU-18,Dexter Ave & Denny Way,47.618285,-122.342205,10/13/2014,20,11/2/2015,0,7/2/2016,10